aws-samples/aws-microservices-deploy-options

- apps/k8s/standalone/manifest.yml
- readme.adoc
**Why:**
* This is just a standalone k8s manifest built from `helm`'s output
**This change addresses the need by:**
* closes #12
Signed-off-by: Christopher Hein <me@christopherhein.com>
> Adding Standalone K8s Configuration

- readme.adoc
**This change addresses the need by:**
* closes #13
Signed-off-by: Christopher Hein <me@christopherhein.com>
> Removing Line About It Not Working

- apps/lambda/sam.yaml
- services/greeting/pom.xml
- services/name/pom.xml
- services/pom.xml
- services/webapp/pom.xml
- services/webapp/src/main/java/org/aws/samples/compute/webapp/GreetingController.java
> Minor fixes to Lambda implementation

- apps/lambda/pipeline.yaml
removed pushd and popd comment as they are not available in the build image
> fixed pushd command not found issue

- readme.adoc
Adding instructions to readme for Fargate
> added fargate to readme

- apps/ecs/fargate/templates/greeting.yaml
- apps/ecs/fargate/templates/infrastructure.yaml
- apps/ecs/fargate/templates/master.yaml
- apps/ecs/fargate/templates/name.yaml
- apps/ecs/fargate/templates/webapp.yaml
- readme.adoc
Added output to cloudformation templaate for the ALB hostname, added instructions on how to retrieve the output from cloudformation.
> adding deployment details

- apps/k8s/ksonnet/myapp/app.yaml
- apps/k8s/ksonnet/myapp/components/greeting.jsonnet
- apps/k8s/ksonnet/myapp/components/name.jsonnet
- apps/k8s/ksonnet/myapp/components/params.libsonnet
- apps/k8s/ksonnet/myapp/components/webapp.jsonnet
- apps/k8s/ksonnet/myapp/environments/base.libsonnet
- readme.adoc
**Why:**
* Gives developers a third way to deploy to k8s
**This change addresses the need by:**
* closes #18
Signed-off-by: Christopher Hein <me@christopherhein.com>
> Adding ksonnet Deploy Tools

- apps/k8s/ksonnet/myapp/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
**Why:**
* Without this file it breaks your `ks` cli
**This change addresses the need by:**
* closes #43:
Signed-off-by: Christopher Hein <me@christopherhein.com>
> Adding .ksonnet file so the registry is documented

- readme.adoc
Adding placeholders for new integrations, further cleaning of slides
> Adding placeholders for new integrations, further cleaning of slides

- readme.adoc
> Adding a reference to #55

- apps/lambda/sam.yaml
- apps/lambda/test/env-mac.json
- apps/lambda/test/env-win.json
- services/greeting/pom.xml
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingEndpoint.java
- services/name/pom.xml
- services/name/src/main/java/org/aws/samples/compute/name/Name.java
- services/name/src/main/java/org/aws/samples/compute/name/NameMessageBodyWriter.java
- services/webapp/pom.xml
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappController.java
*Issue #39 :*
Added name id path parameter support in webapp. 
> partial implementation of Issue #39

- .gitignore
- services/greeting/pom.xml
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingEndpoint.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingHandler.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/StartupBean.java
- services/name/pom.xml
- services/name/src/main/java/org/aws/samples/compute/name/NameEndpoint.java
- services/name/src/main/java/org/aws/samples/compute/name/StartupBean.java
- services/pom.xml
- services/webapp/pom.xml
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappController.java
> Cleaning up the list of files to be included for Docker and Lambda profile, also reformatting

- services/greeting/src/main/java/org/aws/samples/compute/greeting/MyApplication.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/StartupBean.java
> Fixes for JAX-RS Singleton

- .gitignore
- services/greeting/pom.xml
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingEndpoint.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/MyApplication.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/StartupBean.java
- services/name/pom.xml
- services/name/src/main/java/org/aws/samples/compute/name/MyApplication.java
- services/name/src/main/java/org/aws/samples/compute/name/NameEndpoint.java
- services/name/src/main/java/org/aws/samples/compute/name/StartupBean.java
- services/webapp/pom.xml
- services/webapp/src/main/java/org/aws/samples/compute/webapp/MyApplication.java
- services/webapp/src/main/java/org/aws/samples/compute/webapp/StartupBean.java
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappController.java
- Startup sequence for each microservice is now getting triggered. This ensures that X-Ray daemon is being contacted.
- Also added/updated slides
> Enabling X-Ray for each microservice + slides

- services/webapp/src/main/java/org/aws/samples/compute/webapp/MyApplication.java
> Fix WebappController not found

- readme.adoc
#67 
Added steps to setup a deployment pipeline using Jenkins X
> Deployment pipeline using Jenkins X

- readme.adoc
> Fixed branding

- readme.adoc
*Issue #, if available:* #100 
> Merging Fargate and ECS sections

- apps/ecs/ec2/taskdefs/greeting.json
- apps/ecs/ec2/taskdefs/name.json
- apps/ecs/ec2/taskdefs/webapp.json
> First shot at taskdefs

- apps/docker/docker-compose.yaml
*Issue #, if available:* #111 
> fixed #111

- config/ecs/ecs-assume-role-policy.yaml
- config/ecs/ecs-instance-role-policy.yaml
- readme.adoc
*Issue #, if available:* #101 
> starting work on #101

- config/ecs/ecs-assume-role-policy.json
> renaming the file

- readme.adoc
> adding more details

- apps/k8s/helm/myapp/templates/greeting-deployment.yaml
- apps/k8s/helm/myapp/templates/name-deployment.yaml
- apps/k8s/helm/myapp/templates/webapp-deployment.yaml
- apps/k8s/helm/myapp/values.yaml
- readme.adoc
- services/greeting/pom.xml
- services/name/pom.xml
- services/pom.xml
- services/webapp/pom.xml
*Issue #, if available:* #123 
> Fixed #123

- readme.adoc
*Issue #, if available:* #102 #126 
> Fixed #102 #126

- readme.adoc
…/issues/132
*Issue #, if available:* #132 
> fixed #132

- readme.adoc
- services/greeting/src/main/java/org/aws/samples/compute/greeting/StartupBean.java
- services/name/src/main/java/org/aws/samples/compute/name/StartupBean.java
- services/name/src/main/webapp/WEB-INF/web.xml
- services/webapp/src/main/java/org/aws/samples/compute/webapp/StartupBean.java
- services/webapp/src/main/webapp/WEB-INF/web.xml
*Issue #, if available:* #142 and several other improvements
> Fixed #142 and other improvements

- apps/k8s/helm/myapp/templates/greeting-deployment.yaml
- apps/k8s/helm/myapp/templates/name-deployment.yaml
- apps/k8s/helm/myapp/templates/webapp-deployment.yaml
- apps/k8s/helm/myapp/values.yaml
- readme.adoc
*Issue #, if available:* #139 
> fixed #139

- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingEndpoint.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/MyApplication.java
- services/name/src/main/java/org/aws/samples/compute/name/MyApplication.java
- services/name/src/main/java/org/aws/samples/compute/name/NameEndpoint.java
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappController.java
…/issues/110
*Issue #, if available:* #110 
> fixed #110

- readme.adoc
> Improving flow for Lambda

- apps/lambda/test/env-mac.json
- apps/lambda/test/env-win.json
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingEndpoint.java
- services/greeting/src/main/java/org/aws/samples/compute/greeting/GreetingHandler.java
- services/name/src/main/java/org/aws/samples/compute/name/NameEndpoint.java
- services/name/src/main/java/org/aws/samples/compute/name/NameHandler.java
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappController.java
- services/webapp/src/main/java/org/aws/samples/compute/webapp/WebappHandler.java
*Issue #, if available:* #148 #149 
> Fixed issues

- services/greeting/pom.xml
- services/name/pom.xml
- services/pom.xml
- services/webapp/pom.xml
*Issue #, if available:* #146 
> fixed #146

- readme.adoc
*Issue #, if available:* #65 (work in progress)
> starting work on Kubernetes and CodePipeline

- readme.adoc
*Issue #, if available:* starting to work on #121
> starting work on #121

- readme.adoc
*Issue #, if available:* #102 
> fixed #102

- readme.adoc
> fixed a typo

- apps/ecs/fargate/greeting.json
- apps/ecs/fargate/name.json
- apps/ecs/fargate/webapp.json
#135 
Created Fargate taskdefs for name, greeting, and webapp.
> Add Fargate taskdefs

- readme.adoc
> updated command for #151

- readme.adoc
> more work on #135

- readme.adoc
> added placeholder for #82

- readme.adoc
> refactoring the section, starting work on #51

- readme.adoc
> added some more clarifications

- readme.adoc
> More updates

- apps/ecs/ec2/taskdefs/greeting.json
- apps/ecs/ec2/taskdefs/name.json
- apps/ecs/ec2/taskdefs/webapp.json
#135 
Fixed formatting, changed cpu/mem
> For #135: Update ECS EC2 task definitions

- readme.adoc
…/issues/169
*Issue #, if available:* #169 
> fixed #169

- readme.adoc
> formatting Markdown to AsciiDoc

- readme.adoc
> minor formatting for kubepack

- readme.adoc
> Simplify delete operation for kubepack

- readme.adoc
> starting work on #51

- readme.adoc
> Clarified some text

- readme.adoc
*Issue #, if available:* #192 
> formatting

- readme.adoc
> reordered a section

- readme.adoc
> simplified formatting

- apps/lambda/sam.yaml
- readme.adoc
*Issue #, if available:* #201 #202 
> fixed issues and content cleanup

- readme.adoc
*Issue #, if available:* #204 
> fixed issue and general cleanup

- apps/lambda/greeting-sam.yaml
- apps/lambda/name-sam.yaml
- apps/lambda/webapp-sam.yaml
- readme.adoc
*Issue #210 , if available:*
Updated readme.adoc and template output names
> Updated readme.adoc and template output names

- apps/lambda/microservice-pipeline.yaml
*Issue #210 , if available:*
added SSM permissions for the webapp pipeline
> added SSM permissions for the webapp pipeline

- apps/lambda/greeting-sam.yaml
- apps/lambda/hooks/postTrafficHook.js
- apps/lambda/hooks/preTrafficHook.js
- apps/lambda/microservice-pipeline.yaml
- readme.adoc
implemented blue/green deployment for greeting function
> Canary Deployment for Greeting Function

- readme.adoc
> reordered sections and formatting

- apps/lambda/greeting-sam.yaml
*Issue #223 
Replaced hardcoded CanryDeploymentType with parameter
> Fix issue #223. Replaced hardcoded CanryDeploymentType

- apps/ecs/deployment/deployment-pipeline-webapp.yaml
- apps/ecs/deployment/ecs-refarch-continuous-deployment.yaml
- apps/ecs/deployment/load-balancer.yaml
- apps/ecs/deployment/name.yaml
- apps/ecs/deployment/webapp.yaml
- readme.adoc
#82 
Added support for webapp service and pipeline. Also updated readme.adoc. 
> added support for webapp service and pipeline.

- apps/ecs/deployment/ecs-refarch-continuous-deployment.yaml
- readme.adoc
*Issue #, if available:* #225 
> fixed issue #225

- apps/ecs/deployment/ecs-refarch-continuous-deployment.yaml
> removing a redundant parameter

- apps/ecs/deployment/ecs-refarch-continuous-deployment.yaml
- readme.adoc
#82 
Updated templates to account for new location. 
> Updating templates to account for new location of files. 

- readme.adoc
…/issues/104
*Issue #, if available:* #104
> fixed issue #104

- readme.adoc
*Issue #, if available:* https://github.com/arun-gupta/microservices-greeting/issues/3
> docker:push is working

- apps/k8s/canary/manifest.yaml
- apps/k8s/canary/route.yaml
- readme.adoc
*Issue #, if available:* starting work on #189 #233 
> starting work on Istio issues

- apps/k8s/istio/manifest.yaml
- apps/k8s/istio/route-50-50.yaml
- apps/k8s/istio/route-90-10.yaml
- apps/k8s/istio/route-greeting-delay-10percent.yaml
- readme.adoc
*Issue #, if available:* further work on #189 
> more work on #189

- readme.adoc
*Issue #, if available:* #233 
> fixing the title

- readme.adoc
*Issue #, if available:* #189 
> fixed #189

- apps/ecs/deployment/load-balancer.yaml
- apps/ecs/deployment/vpc.yaml
> Fixed issues with security group rules and healthcheck for name service.

- readme.adoc
> updating readme for #60

- apps/ecs/deployment/webapp.yaml
> fixed issue

- readme.adoc
> added a link

- apps/ecs/fargate/templates/webapp.yaml
- apps/lambda/microservice-pipeline.yaml
- readme.adoc
*Issue #, if available:* some more changes for #247 
> formatting and name changes for #247

- apps/ecs/ec2/taskdefs/webapp.json
- readme.adoc
> rehearsing the flow for #DevoxxFR

- readme.adoc
> Cleaned up flow and rehearsal for #DevoxxFR

- readme.adoc
*Issue #, if available:* #251 
> fixed issue and content update

- readme.adoc
> refactoring Lambda canary deployment section

- apps/lambda/microservice-pipeline.yaml
This allows the GitHubBranch parameter to be correctly used (rather than using the GitHubOwner as branch)
> fixed reference to GitHubBranch

- readme.adoc
…loy-options/issues/88
*Issue #, if available:* starting work on #88 
> starting work on #88

- readme.adoc
#66 
Tried creating relative URLs for Spinnaker and Skaffold, but Github was not applying markdown correctly in my forked repo. 
> Adding TOC headings for Spinnaker and Skaffold

- readme.adoc
> changing MD to ADOC

- LICENSE
- NOTICE
- readme.adoc
> Relicensing to MIT-0

- readme.adoc
> Fix fargate only supported in us-east-1 note
